In [1]:
import pandas as pd

In [4]:
data = {'Name': ['Alice', 'Bob'], 'Age': [25, 30]}
df = pd.DataFrame(data)
print(df)

    Name  Age
0  Alice   25
1    Bob   30

In [5]:
lst = [['Alice', 25], ['Bob', 30]]
df = pd.DataFrame(lst, columns=['Name', 'Age'])
print(df)

    Name  Age
0  Alice   25
1    Bob   30

In [6]:
df.head()

    Name  Age
0  Alice   25
1    Bob   30

In [7]:
df.tail()

    Name  Age
0  Alice   25
1    Bob   30

In [8]:

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

In [9]:

df.describe()

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [10]:
df['Name']
df[['Name', 'Age']]

    Name  Age
0  Alice   25
1    Bob   30

In [11]:
df.loc[0]
df.iloc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [12]:
df[df['Age'] > 25]

  Name  Age
1  Bob   30

In [14]:
df['Gender'] = ['F', 'M']
print(df)

    Name Gender
0  Alice      F
1    Bob      M

In [25]:
data = {'Name': ['Alice', 'Bob'], 'Age': [25, 30]}
df = pd.DataFrame(data)
df.drop('Age', axis=1, inplace=True)
print(df)
print(df.columns)

    Name
0  Alice
1    Bob
Index(['Name'], dtype='str')

In [26]:
df.isnull()

    Name
0  False
1  False

In [18]:

df.dropna()

    Name
0  Alice
1    Bob

In [19]:

df.fillna(0)

    Name
0  Alice
1    Bob

In [28]:
data = {'Name': ['Alice', 'Bob'], 'Age': [25, 30]}
df = pd.DataFrame(data)
df['Gender']=['F', 'M']
print(df)
df.groupby('Gender')['Age'].mean()

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M

Gender
F    25.0
M    30.0
Name: Age, dtype: float64

In [32]:
df1 = pd.DataFrame({'Key':[1, 2],
                    'Name':['Alice', 'Bob']
                   })
df2 = pd.DataFrame({'Key':[1, 2],
                    'Age':[25, 30]
                   })
result = pd.merge(df1,df2,on='Key')
print(result)

   Key   Name  Age
0    1  Alice   25
1    2    Bob   30

In [33]:
df1 = pd.DataFrame({
    'Name':

ValueError: columns overlap but no suffix specified: Index(['Key'], dtype='str')